---
- name: Get grafana gpg key
  become: true
  ansible.builtin.get_url:
    url: https://apt.grafana.com/gpg.key
    dest: /usr/share/keyrings/grafana.key

- name: Add grafana repository
  become: true
  apt_repository:
    repo: "deb [signed-by=/usr/share/keyrings/grafana.key] https://apt.grafana.com stable main"
    state: present

- name: Update apt list
  become: true
  apt:
    update_cache: true

- name: Install grafana
  become: true
  package:
    state: present
    name: grafana

- name: Create postgres db
  community.postgresql.postgresql_db:
    port: "{{ postgres.port }}"
    login_password: "{{ secret.postgres.password }}"
    name: grafana
    state: present
    encoding: UTF-8
    template: template0

- name: Create postgres user
  community.postgresql.postgresql_user:
    port: "{{ postgres.port }}"
    login_password: "{{ secret.postgres.password }}"
    db: grafana
    name: graf
    state: present
    password: "{{ secret.postgres.grafana_password }}"
    comment: User for Grafana

- name: Set grafana port
  become: true
  lineinfile:
    path: /etc/grafana/grafana.ini
    line: "http_port = {{ grafana.port }}"
    search_string: "http_port = "
    state: present

- name: Restart grafana
  become: true
  service:
    name: grafana-server
    state: restarted
    enabled: true