---
- hosts: dev
  gather_facts: true
  vars:
    ansible_user: "{{ username }}"
    deb_architecture: 
      armv6l: armhf
      armv7l: armhf
      aarch64: arm64
      x86_64: amd64
      i386: i386
  roles:
    - role: system
      tags:
        - system
        - dev

    - role: node
      tags:
        - node
        - dev

    - role: python
      tags:
        - python
        - dev

    - role: docker
      tags:
        - docker
        - dev
      when: '"docker" in extra_roles'

    - role: gitea
      tags:
        - gitea
        - dev
      when: '"gitea" in {{ extra_roles }}'

    - role: code-server
      tags:
        - code-server
        - dev
      when: '"code-server" in {{ extra_roles }}'