---
nextcloud:
  install_path: /var/www/nextcloud
  database:
    name: nextcloud
    user: next
    dir: /var/www/nextcloud-data
  exposed_port: 3443
  dependencies:
    - imagemagick
    - nginx
    - postgres
    - php8.1
    - php-imagick
    - php8.1-common
    - php8.1-pgsql
    - php8.1-fpm
    - php8.1-gd
    - php8.1-curl
    - php8.1-imagick
    - php8.1-zip
    - php8.1-xml
    - php8.1-mbstring
    - php8.1-bz2
    - php8.1-intl
    - php8.1-bcmath
    - php8.1-gmp