---
- include_tasks: essentials.yml
- include_tasks: nginx.yml
  when: '"nginx" in {{ extra_packages }}'
- include_tasks: postgres.yml
  when: '"postgresql" in {{ extra_packages }}'
- include_tasks: cloudflared.yml
  when: '"cloudflared" in {{ extra_roles }}'
