---
- name: Download and install from installer
  become: true
  apt:
    state: present
    deb: https://github.com/coder/code-server/releases/download/v{{ code-server.version }}/code-server_{{ code-server.version }}_{{ deb_architecture[ansible_architecture] }}.deb

- name: Enable and start code-server
  become: true
  service:
    name: code-server@{{ username }}
    state: restarted
    enabled: true
    masked: false